// Code generated by ent, DO NOT EDIT.

package ent

import (
	"composeapp/ent/categories"
	"composeapp/ent/schema"
	"composeapp/ent/settings"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoriesFields := schema.Categories{}.Fields()
	_ = categoriesFields
	// categoriesDescParentID is the schema descriptor for parent_id field.
	categoriesDescParentID := categoriesFields[0].Descriptor()
	// categories.DefaultParentID holds the default value on creation for the parent_id field.
	categories.DefaultParentID = categoriesDescParentID.Default.(int)
	// categoriesDescName is the schema descriptor for name field.
	categoriesDescName := categoriesFields[1].Descriptor()
	// categories.DefaultName holds the default value on creation for the name field.
	categories.DefaultName = categoriesDescName.Default.(string)
	// categoriesDescSystemName is the schema descriptor for system_name field.
	categoriesDescSystemName := categoriesFields[2].Descriptor()
	// categories.DefaultSystemName holds the default value on creation for the system_name field.
	categories.DefaultSystemName = categoriesDescSystemName.Default.(string)
	// categoriesDescDescription is the schema descriptor for description field.
	categoriesDescDescription := categoriesFields[3].Descriptor()
	// categories.DefaultDescription holds the default value on creation for the description field.
	categories.DefaultDescription = categoriesDescDescription.Default.(string)
	settingsFields := schema.Settings{}.Fields()
	_ = settingsFields
	// settingsDescCategoryID is the schema descriptor for category_id field.
	settingsDescCategoryID := settingsFields[0].Descriptor()
	// settings.CategoryIDValidator is a validator for the "category_id" field. It is called by the builders before save.
	settings.CategoryIDValidator = settingsDescCategoryID.Validators[0].(func(int) error)
	// settingsDescName is the schema descriptor for name field.
	settingsDescName := settingsFields[1].Descriptor()
	// settings.DefaultName holds the default value on creation for the name field.
	settings.DefaultName = settingsDescName.Default.(string)
	// settingsDescValue is the schema descriptor for value field.
	settingsDescValue := settingsFields[2].Descriptor()
	// settings.DefaultValue holds the default value on creation for the value field.
	settings.DefaultValue = settingsDescValue.Default.(string)
	// settingsDescUID is the schema descriptor for uid field.
	settingsDescUID := settingsFields[3].Descriptor()
	// settings.UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	settings.UIDValidator = settingsDescUID.Validators[0].(func(int) error)
	// settingsDescCreated is the schema descriptor for created field.
	settingsDescCreated := settingsFields[4].Descriptor()
	// settings.DefaultCreated holds the default value on creation for the created field.
	settings.DefaultCreated = settingsDescCreated.Default.(int)
	// settingsDescActuality is the schema descriptor for actuality field.
	settingsDescActuality := settingsFields[5].Descriptor()
	// settings.DefaultActuality holds the default value on creation for the actuality field.
	settings.DefaultActuality = settingsDescActuality.Default.(int)
}
