// Code generated by ent, DO NOT EDIT.

package ent

import (
	"composeapp/ent/predicate"
	"composeapp/ent/settings"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SettingsUpdate is the builder for updating Settings entities.
type SettingsUpdate struct {
	config
	hooks    []Hook
	mutation *SettingsMutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (su *SettingsUpdate) Where(ps ...predicate.Settings) *SettingsUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetCategoryID sets the "category_id" field.
func (su *SettingsUpdate) SetCategoryID(i int) *SettingsUpdate {
	su.mutation.ResetCategoryID()
	su.mutation.SetCategoryID(i)
	return su
}

// AddCategoryID adds i to the "category_id" field.
func (su *SettingsUpdate) AddCategoryID(i int) *SettingsUpdate {
	su.mutation.AddCategoryID(i)
	return su
}

// SetName sets the "name" field.
func (su *SettingsUpdate) SetName(s string) *SettingsUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableName(s *string) *SettingsUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetValue sets the "value" field.
func (su *SettingsUpdate) SetValue(s string) *SettingsUpdate {
	su.mutation.SetValue(s)
	return su
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableValue(s *string) *SettingsUpdate {
	if s != nil {
		su.SetValue(*s)
	}
	return su
}

// SetUID sets the "uid" field.
func (su *SettingsUpdate) SetUID(i int) *SettingsUpdate {
	su.mutation.ResetUID()
	su.mutation.SetUID(i)
	return su
}

// AddUID adds i to the "uid" field.
func (su *SettingsUpdate) AddUID(i int) *SettingsUpdate {
	su.mutation.AddUID(i)
	return su
}

// SetCreated sets the "created" field.
func (su *SettingsUpdate) SetCreated(i int) *SettingsUpdate {
	su.mutation.ResetCreated()
	su.mutation.SetCreated(i)
	return su
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableCreated(i *int) *SettingsUpdate {
	if i != nil {
		su.SetCreated(*i)
	}
	return su
}

// AddCreated adds i to the "created" field.
func (su *SettingsUpdate) AddCreated(i int) *SettingsUpdate {
	su.mutation.AddCreated(i)
	return su
}

// SetActuality sets the "actuality" field.
func (su *SettingsUpdate) SetActuality(i int) *SettingsUpdate {
	su.mutation.ResetActuality()
	su.mutation.SetActuality(i)
	return su
}

// SetNillableActuality sets the "actuality" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableActuality(i *int) *SettingsUpdate {
	if i != nil {
		su.SetActuality(*i)
	}
	return su
}

// AddActuality adds i to the "actuality" field.
func (su *SettingsUpdate) AddActuality(i int) *SettingsUpdate {
	su.mutation.AddActuality(i)
	return su
}

// Mutation returns the SettingsMutation object of the builder.
func (su *SettingsUpdate) Mutation() *SettingsMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SettingsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SettingsUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SettingsUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SettingsUpdate) check() error {
	if v, ok := su.mutation.CategoryID(); ok {
		if err := settings.CategoryIDValidator(v); err != nil {
			return &ValidationError{Name: "category_id", err: fmt.Errorf(`ent: validator failed for field "Settings.category_id": %w`, err)}
		}
	}
	if v, ok := su.mutation.UID(); ok {
		if err := settings.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "Settings.uid": %w`, err)}
		}
	}
	return nil
}

func (su *SettingsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.CategoryID(); ok {
		_spec.SetField(settings.FieldCategoryID, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedCategoryID(); ok {
		_spec.AddField(settings.FieldCategoryID, field.TypeInt, value)
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(settings.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.Value(); ok {
		_spec.SetField(settings.FieldValue, field.TypeString, value)
	}
	if value, ok := su.mutation.UID(); ok {
		_spec.SetField(settings.FieldUID, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedUID(); ok {
		_spec.AddField(settings.FieldUID, field.TypeInt, value)
	}
	if value, ok := su.mutation.Created(); ok {
		_spec.SetField(settings.FieldCreated, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedCreated(); ok {
		_spec.AddField(settings.FieldCreated, field.TypeInt, value)
	}
	if value, ok := su.mutation.Actuality(); ok {
		_spec.SetField(settings.FieldActuality, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedActuality(); ok {
		_spec.AddField(settings.FieldActuality, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SettingsUpdateOne is the builder for updating a single Settings entity.
type SettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SettingsMutation
}

// SetCategoryID sets the "category_id" field.
func (suo *SettingsUpdateOne) SetCategoryID(i int) *SettingsUpdateOne {
	suo.mutation.ResetCategoryID()
	suo.mutation.SetCategoryID(i)
	return suo
}

// AddCategoryID adds i to the "category_id" field.
func (suo *SettingsUpdateOne) AddCategoryID(i int) *SettingsUpdateOne {
	suo.mutation.AddCategoryID(i)
	return suo
}

// SetName sets the "name" field.
func (suo *SettingsUpdateOne) SetName(s string) *SettingsUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableName(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetValue sets the "value" field.
func (suo *SettingsUpdateOne) SetValue(s string) *SettingsUpdateOne {
	suo.mutation.SetValue(s)
	return suo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableValue(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetValue(*s)
	}
	return suo
}

// SetUID sets the "uid" field.
func (suo *SettingsUpdateOne) SetUID(i int) *SettingsUpdateOne {
	suo.mutation.ResetUID()
	suo.mutation.SetUID(i)
	return suo
}

// AddUID adds i to the "uid" field.
func (suo *SettingsUpdateOne) AddUID(i int) *SettingsUpdateOne {
	suo.mutation.AddUID(i)
	return suo
}

// SetCreated sets the "created" field.
func (suo *SettingsUpdateOne) SetCreated(i int) *SettingsUpdateOne {
	suo.mutation.ResetCreated()
	suo.mutation.SetCreated(i)
	return suo
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableCreated(i *int) *SettingsUpdateOne {
	if i != nil {
		suo.SetCreated(*i)
	}
	return suo
}

// AddCreated adds i to the "created" field.
func (suo *SettingsUpdateOne) AddCreated(i int) *SettingsUpdateOne {
	suo.mutation.AddCreated(i)
	return suo
}

// SetActuality sets the "actuality" field.
func (suo *SettingsUpdateOne) SetActuality(i int) *SettingsUpdateOne {
	suo.mutation.ResetActuality()
	suo.mutation.SetActuality(i)
	return suo
}

// SetNillableActuality sets the "actuality" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableActuality(i *int) *SettingsUpdateOne {
	if i != nil {
		suo.SetActuality(*i)
	}
	return suo
}

// AddActuality adds i to the "actuality" field.
func (suo *SettingsUpdateOne) AddActuality(i int) *SettingsUpdateOne {
	suo.mutation.AddActuality(i)
	return suo
}

// Mutation returns the SettingsMutation object of the builder.
func (suo *SettingsUpdateOne) Mutation() *SettingsMutation {
	return suo.mutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (suo *SettingsUpdateOne) Where(ps ...predicate.Settings) *SettingsUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SettingsUpdateOne) Select(field string, fields ...string) *SettingsUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Settings entity.
func (suo *SettingsUpdateOne) Save(ctx context.Context) (*Settings, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SettingsUpdateOne) SaveX(ctx context.Context) *Settings {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SettingsUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SettingsUpdateOne) check() error {
	if v, ok := suo.mutation.CategoryID(); ok {
		if err := settings.CategoryIDValidator(v); err != nil {
			return &ValidationError{Name: "category_id", err: fmt.Errorf(`ent: validator failed for field "Settings.category_id": %w`, err)}
		}
	}
	if v, ok := suo.mutation.UID(); ok {
		if err := settings.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "Settings.uid": %w`, err)}
		}
	}
	return nil
}

func (suo *SettingsUpdateOne) sqlSave(ctx context.Context) (_node *Settings, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Settings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settings.FieldID)
		for _, f := range fields {
			if !settings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != settings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.CategoryID(); ok {
		_spec.SetField(settings.FieldCategoryID, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedCategoryID(); ok {
		_spec.AddField(settings.FieldCategoryID, field.TypeInt, value)
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(settings.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Value(); ok {
		_spec.SetField(settings.FieldValue, field.TypeString, value)
	}
	if value, ok := suo.mutation.UID(); ok {
		_spec.SetField(settings.FieldUID, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedUID(); ok {
		_spec.AddField(settings.FieldUID, field.TypeInt, value)
	}
	if value, ok := suo.mutation.Created(); ok {
		_spec.SetField(settings.FieldCreated, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedCreated(); ok {
		_spec.AddField(settings.FieldCreated, field.TypeInt, value)
	}
	if value, ok := suo.mutation.Actuality(); ok {
		_spec.SetField(settings.FieldActuality, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedActuality(); ok {
		_spec.AddField(settings.FieldActuality, field.TypeInt, value)
	}
	_node = &Settings{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
