// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Categories is the predicate function for categories builders.
type Categories func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)
